### PR TITLE
adding main kubescape repositories

### PR DESCRIPTION
**Pull request by matthyx**

### CODE REVIEW

**Comment by tegioz** [comment]
Thanks @matthyx!

Just in case you didn't know, you can adjust the check sets for each repository to the one that suits it best if you'd like. The list of available checks sets can be found [here](https://clomonitor.io/docs/topics/checks/). For example, it's common to have a single repository with the `community` check set, and Helm charts repo sometimes use `code-lite`. But it's up to you 🙂

**Comment by matthyx** [comment]
> Thanks @matthyx!
> 
> Just in case you didn't know, you can adjust the check sets for each repository to the one that suits it best if you'd like. The list of available checks sets can be found [here](https://clomonitor.io/docs/topics/checks/). For example, it's common to have a single repository with the `community` check set, and Helm charts repo sometimes use `code-lite`. But it's up to you 🙂

Nice, I didn't know... let me read the checks and update my PR!

**Comment by matthyx** [comment]
@tegioz I think it's more representative now, thanks for your efficiency!

**Comment by tegioz** [comment]
No worries, happy to help 🙂

**Review by tegioz — APPROVED** [review]

**Pull request merged**
