### PR TITLE
feat: add more repositories for kepler

### LINKED ISSUE #1244: Add more repos for kepler project
Right now only the kepler repo is added for the kepler project but it consists of more repos that can be integrated:

https://github.com/sustainable-computing-io/kepler-model-server
https://github.com/sustainable-computing-io/kepler-operator
https://github.com/sustainable-computing-io/kepler-helm-chart
https://github.com/sustainable-computing-io/kepler-model-db
https://github.com/sustainable-computing-io/kepler-action
https://github.com/sustainable-computing-io/kepler-estimator
https://github.com/sustainable-computing-io/kepler-doc

There is more but I think those are the most relevant as they contain issues.

### PR DESCRIPTION
**Pull request by BGrasnick**
fixes #1244

### CODE REVIEW

**Comment by rootfs** [comment]
@BGrasnick this is great!

**Comment by tegioz** [comment]
Thanks @BGrasnick! 

Have you considered using a different check set for some of those repositories? I'm mentioning it because it looks like some of them won't pass some of the checks for each of the sets, and the overall Kepler score will get worse. If this is intentional then we can merge as it is, it's not a problem. However, if some of these repositories are not expected to have -let's say- the community content, maybe it'd be better to not use that check set on them.

The check sets available at the moment are: `code`, `code-lite`, `community`and `docs`, and it's possible to use one or more on each repo. You can find the list of checks CLOMonitor runs for each set [here](https://clomonitor.io/docs/topics/checks/).

Hope this helps 🙂

**Comment by BGrasnick** [comment]
@tegioz thank you so much for the advice! I'll look into it and update the PR!

**Comment by BGrasnick** [comment]
@tegioz I think it should be better and more appropriate now!
@rootfs if you want please also check if that fits better :)

**Comment by tegioz** [comment]
Awesome! Happy to merge when you are ready 🙂

Please note that [CLOTributor](https://clotributor.dev) will also start processing those repositories as well to collect issues 😉 It's possible to disable that if you only want CLOMonitor to use them though.

**Comment by rootfs** [comment]
thank you @tegioz for the pointers and @BGrasnick for the PR, `code-lite` is a good choice

**Pull request merged**
