### PR TITLE
Add CNCF tags to CLOTributor

### PR DESCRIPTION
**Pull request by aliok**
- Add CNCF tags to [CLOTributor](https://clotributor.dev/), so that `help wanted` issues are shown there
- TAGs won't show up in [CLOMonitor](https://clomonitor.io/search?page=1) though

### CODE REVIEW

**Comment by aliok** [comment]
Does anybody know a good way of reaching out TAGs and letting them know about this change? ...other than going individually to their Slack channels and posting a message :) ? Is there a GitHub user group or something that I can mention the chairs?

**Review by tegioz — APPROVED** [review]
Thanks @aliok! 👍

**Comment by tegioz** [comment]
<https://clotributor.dev/search?ts_query_web=cncf-tag&page=1> 🙂

**Comment by tegioz** [comment]
@aliok please note that CLOTributor searches for issues that contain the `help wanted` label, but it looks like some TAGs are using variants like `help-wanted` (like [tag-contributor-strategy](https://github.com/cncf/tag-contributor-strategy/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp-wanted)). It'd be great if that label could be renamed if it's not a problem for other use cases.

**Comment by aliok** [comment]
> @aliok please note that CLOTributor searches for issues that contain the help wanted label, but it looks like some TAGs are using variants like help-wanted (like [tag-contributor-strategy](https://github.com/cncf/tag-contributor-strategy/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp-wanted)). It'd be great if that label could be renamed if it's not a problem for other use cases.

@tegioz Can't we also include `help-wanted` in CLOTributor search? That might be a lot easier and I don't see it causing any disruption on CLOTributor. What do you think?

**Comment by tegioz** [comment]
> @tegioz Can't we also include `help-wanted` in CLOTributor search? That might be a lot easier and I don't see it causing any disruption on CLOTributor. What do you think?

I was explaining why this hadn't been done before, should have done that in my previous comment 😇

In other situations, CLOTributor accepts variants for the labels. But this one is a bit special.

The first thing we do when processing a repository is searching for all issues that contain a specific set of labels (in this case, `help wanted`), by using the GraphQL GitHub API. That API allows us to filter issues that contain one or more labels, but not searching for issues that contain label-a *or* label-b. This means that to support variants in this case, we'd need to do an extra search request for each variant (more could be requested eventually). And we wanted to avoid that to avoid hitting the GitHub API rate limits earlier than strictly needed (those search queries can be expensive), as this could be a problem as we grow.

Other situations are handled once we've fetched the full issue. In those cases no further GitHub API requests are needed and we can do all processing on our end, so checking for variants won't cause any problems.

IIRC by renaming the label on the labels view, it'll be renamed on all issues automatically, so hopefully this is not a problem (unless it's being used as it is by another application).

**Comment by aliok** [comment]
@tegioz Fair enough :) Thanks for the explanation.

**Comment by aliok** [comment]
I "spammed" Slack channels of TAGs now with information about CLOTributor :)

Interestingly, TAG Contributor Strategy is the only TAG that's using `help-wanted` instead of `help wanted`.

**Comment by tegioz** [comment]
> I "spammed" Slack channels of TAGs now with information about CLOTributor :)

Awesome! 😉

> Interestingly, TAG Contributor Strategy is the only TAG that's using `help-wanted` instead of `help wanted`.

Cool, the less trouble this causes, the better 😇

**Pull request merged**
