### PR TITLE
add Nephio

### PR DESCRIPTION
**Pull request by VedRatan**
Proposal to add Nephio project for active evaluation by CLOMonitor.

### CODE REVIEW

**Comment by tegioz** [comment]
Hi @VedRatan 👋

Thanks for your interest in CLOMonitor! Before adding Nephio to CLOMonitor, we'd need to add LF Networking to it. I see you've added the project to the Continuous Delivery Foundation (as LFN isn't there yet), but it'd be best if we add LFN to CLOMonitor add include Nephio as part of it. We'll try to take care of this soon, we'll keep you posted 🙂

**Comment by VedRatan** [comment]
Hi @tegioz thanks for considering this PR, just wanted to know do I have to raise a PR to add LFN to CLOMonitor or will you be handling the same. Thanks!

**Comment by tegioz** [comment]
We'll take care of it, leave it with us 🙂 Thanks!

**Comment by tegioz** [comment]
Hi @VedRatan

We've just added LF Networking to CLOMonitor and CLOTributor. Feel free to make any adjustments needed to the data file (i.e. update check sets, add/remove any repository, etc).

Thanks!

**Pull request closed without merging**
