### PR TITLE
Update cncf.yaml - review check_sets for Score

### PR DESCRIPTION
**Pull request by mathieu-benoit**
According to https://clomonitor.io/docs/topics/checks, review the `check_sets` for the different repos/projects of Score.

### CODE REVIEW

**Review by tegioz — APPROVED** [review]
Thanks @mathieu-benoit 👍

**Comment by tegioz** [comment]
Hi @mathieu-benoit

One of the repositories should have the `community` check set (probably `spec`?), I overlooked this when reviewing it before. Could you please fix it? Thanks!

**Comment by mathieu-benoit** [comment]
@tegioz, oh ok, gotcha, sorry about that and makes sense, just did: https://github.com/cncf/clomonitor/pull/1637. Thanks!

**Comment by tegioz** [comment]
Thank you!

**Pull request merged**
