### PR TITLE
Add more Knative-sandbox repos for CLOTributor

### PR DESCRIPTION
**Pull request by aliok**
Add more Knative-sandbox repos for CLOTributor

Related: https://github.com/cncf/clomonitor/pull/1074

### CODE REVIEW

**Comment by aliok** [comment]
/hold

Wrong URLs!

**Review by tegioz — APPROVED** [review]
Thanks @aliok!

**Comment by tegioz** [comment]
It looks like GitHub [is having some issues now](https://www.githubstatus.com).

**Pull request merged**
