### PR TITLE
Update lfenergy.yaml

### PR DESCRIPTION
**Pull request by jmertic**

### CODE REVIEW

**Comment by jmertic** [comment]
@tegioz The logo links are fixed, but still working on the archived and private repos; waiting for an upstream landscapeapp fix

**Comment by tegioz** [comment]
Thanks @jmertic 👍

**Review by tegioz — CHANGES_REQUESTED** [review]
Hi @jmertic

I've just tested a few of them but they don't seem to be working for me. Can you please take a look? Thanks!

<https://artwork.lfenergy.org/horizontal/color/everest-horizontal-color.svg>
<https://artwork.lfenergy.org/abbrev/color/grid-exchange-fabric-abbrev-color.svg>
<https://artwork.lfenergy.org/horizontal/color/seapath-horizontal-color.svg>

**Comment by jmertic** [comment]
Whoopsie - fixed now :-). Thanks for catching that!

**Review by tegioz — APPROVED** [review]
Thanks!

**Pull request merged**
