### PR TITLE
Add missing Kubewarden repositories

### PR DESCRIPTION
**Pull request by raulcabello**
Add the following repositories for Kubewarden:
- [kwctl](https://github.com/kubewarden/kwctl)
- [policy-sdk-rust](https://github.com/kubewarden/policy-sdk-rust)
- [policy-sdk-go](https://github.com/kubewarden/policy-sdk-go)
- [policy-sdk-swift](https://github.com/kubewarden/policy-sdk-swift)
- [policy-sdk-dotnet](https://github.com/kubewarden/policy-sdk-dotnet)

Add `community` and `code` check_set for `policy-server`

### CODE REVIEW

**Review by tegioz — DISMISSED** [review]
Thanks for the PR @raulcabello!

**Comment by tegioz** [comment]
We usually only assign the `community` check set to the "main" project's repo (or to a dedicated repo with that kind of documentation) as the checks on it check for items that may not be present on all repos. But it's completely fine to add it to more if you'd like. It may make a bit harder to get a good score, but everything will be better 😉

**Comment by tegioz** [comment]
You can see the checks run on each set [here](https://clomonitor.io/docs/topics/checks/), just in case you change your mind (I'll hold on a bit before merging until you confirm). Maybe I shouldn't have said better @raulcabello, as some of them will be redundant and may make maintenance a bit harder on your side. But up to you 🙂 

Just for reference, these are the checks on the `community` set as of today:

- Documentation / Adopters
- Documentation / Code of conduct
- Documentation / Contributing
- Documentation / Governance
- Documentation / Readme
- Documentation / Roadmap
- Documentation / Website
- Best practices / Analytics
- Best practices / Community meeting
- Best practices / GitHub discussions
- Best practices / Slack presence
- Security / Policy
- Legal / Trademark disclaimer

**Comment by raulcabello** [comment]
Thanks for the quick response and for the suggestion @tegioz! :smile: 
We'll leave just the `kubewarden-controller` with the `community` chek

**Review by tegioz — APPROVED** [review]

**Pull request merged**
