### PR TITLE
Adds argo-site repo

### PR DESCRIPTION
**Pull request by chalin**
/cc @nate-double-u 

Signed-off-by: Patrice Chalin <chalin@users.noreply.github.com>

### CODE REVIEW

**Review by tegioz — APPROVED** [review]
Thanks! 👍

**Comment by chalin** [comment]
Any idea why the new repo isn't yet showing up? https://clomonitor.io/projects/cncf/argo/argo

**Comment by tegioz** [comment]
Hi @chalin

Yes, we haven't deployed this change yet. We'll do it a bit later today.

**Comment by tegioz** [comment]
Deployed!

**Pull request merged**
