### PR TITLE
Add aswf.yaml

### PR DESCRIPTION
**Pull request by jmertic**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206174275472287

### CODE REVIEW

**Review by tegioz — CHANGES_REQUESTED** [review]
Thanks @jmertic!

Could you please add the corresponding [check sets](https://clomonitor.io/docs/topics/checks/) for each repository?

**Comment by jmertic** [comment]
Hey - happy to do this - but since we don't plan to use clomonitor right now, what is the minimal level of checks we should do?

**Comment by tegioz** [comment]
Oh cool, then instead of adding the checks set, it'd be best to exclude them from CLOMonitor. You can achieve that by adding the following to each repository:

```yaml
exclude:
  - clomonitor
```

**Comment by jmertic** [comment]
Sounds good - take a look and see if that is better now.

**Pull request merged**
