### PR TITLE
Update cncf.yaml - More repos for Score

### PR DESCRIPTION
**Pull request by mathieu-benoit**
Adding more repos for the Score project to provide more visibility here https://clomonitor.io/projects/cncf/score and also allowing to have their `good first issues` listed here: https://clotributor.dev/search?foundation=cncf&project=score.

Also, updated and classified the `checks`'s types according to: https://github.com/cncf/clomonitor/blob/main/docs/checks.md.

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
Ready for your review, thanks!

**Review by tegioz — APPROVED** [review]

**Comment by tegioz** [comment]
Thanks @mathieu-benoit 👍

**Comment by mathieu-benoit** [comment]
Thanks @tegioz! Just for my information, do you know when I could expect to have the https://clotributor.dev/search?foundation=cncf&project=score updated accordingly? In the main README.md, it says "periodically every hour", but not sure about that.

**Comment by tegioz** [comment]
No worries!

Yes, every hour. Could you point me to some issues you'd expect to have been indexed?

Please note that, as mentioned in the [repository's readme file](https://github.com/cncf/clotributor?tab=readme-ov-file#how-it-works), CLOTributor only indexes issues that match certain criteria:

- Contain the `help wanted` label
- Their state is `OPEN`
- They are `unassigned`
- Updated within the last year

**Comment by mathieu-benoit** [comment]
Sure, for example these ones:
- https://github.com/score-spec/score-compose/issues/179
- https://github.com/score-spec/score-go/issues/47
But I see, that's the `help wanted` label which is missing, fixing this on my end, thanks!

**Pull request merged**
